### PR TITLE
Add an option to feedvalue to put the unit at the front

### PR DESCRIPTION
**Pull request by mattjgalloway**
Useful for £/$ units.

screen shot 2016-09-06 at 16 18 39

### CODE REVIEW

**Comment by Paul-Reed** [comment]
Unit position dropdown is not visible in config.
feedvalue

**Comment by mattjgalloway** [comment]
@Paul-Reed - can you try refreshing? It really should be there, and shows in mine as per screenshot. I've found sometimes you need to refresh a couple of times to make sure everything is updated and not from old cached objects.

**Comment by Paul-Reed** [comment]
I've already ruled that out. Tried 3 different browser with cache cleared, tried incognito window, and also connected by local IP address - same result.

**Comment by mattjgalloway** [comment]
Well that's fun then! Hmm. I'll try and see if I can figure out why - but the code is there to show that text and the box :-/.

**Comment by mattjgalloway** [comment]
@Paul-Reed - I'm totally at a loss. I've checked out this specific branch and it still works for me.

Maybe you could try putting a breakpoint in `widget/feedvalue/feedvalue_render.js` to verify you are indeed hitting the refreshed code when you're testing this?

**Comment by Paul-Reed** [comment]
OK, I've just re-installed dashboard from scratch, this was the sequence;

- Delete existing 'dashboard' directory
- Git clone your dashboard fork
- Rename the directory from 'emoncms-dashboard' to 'dashboard'
- Checkout your 'feedvalue_unit_position branch'
- Git pull - up to date
- Reboot raspberry pi
- Clear browser cache & reload emoncms

Still same result, even tried new mobile devices.

I'll have more time tomorrow night to explore further.

**Comment by mattjgalloway** [comment]
Ugh that's really, really odd. I hope it's something that will magically fix itself for you tomorrow, because I've no idea why it wouldn't be showing it :-(. Thanks for trying!

**Comment by Paul-Reed** [comment]
Sorted! I found another version of feedvalue_render.js on my pi, which I was being picked up instead of the dashboard/widget/feedvalue version.
All good now, no errors and a helpful addition.
Thanks Matt

**Pull request merged**
