### PR TITLE
Add a grid size option to dashboard

### PR DESCRIPTION
**Pull request by mattjgalloway**
This adds an option to dashboard to set the grid size. I noticed that quite a few people have the problem where they want to change this. This enables you to change it.

### CODE REVIEW

**Comment by Paul-Reed** [comment]
Sorry Matt, not working here. I'm getting a console error;

```SyntaxError: expected expression, got '<'```

Following the error, line 231 is highlighted;

debug

emoncms 9.7.2 | 2016.07.04

**Comment by mattjgalloway** [comment]
@Paul-Reed - it adds a new field to `dashboard`. So you need to run database upgrade in admin panel.

**Comment by Paul-Reed** [comment]
A long awaited function!
It would be great if you could raise a quick post in the forum, letting members know of this feature, especially the need to update database. (in emonpi, the update script updates automatically).
Thanks you very much Matt, nicely done.

**Comment by mattjgalloway** [comment]
Sure - I'll post shortly. Just creating some dashboards right now :-).

**Pull request merged**
