### PR TITLE
frostpoints and humidex widgets

### PR DESCRIPTION
**Pull request by thib66**

### CODE REVIEW

**Comment by Paul-Reed** [comment]
Thanks for the PR, however shouldn't widgets be added to the `~/emoncms/Modules/dashboard/widget/` path?
This PR will place your widgets in the `~/emoncms/Modules/dashboard` directory which will not be read by emoncms.

Also... please see the [Codacy report for this PR](https://www.codacy.com/app/emoncms/dashboard/pullRequest?prid=701286) which highlights a number of code quality issues. Could these be improved please.

Paul

**Comment by thib66** [comment]
Hello, 
It is the first time I use github, I think I have placed the files in the correct folders now and fix the most important issues in the code via codacy
Regards,
Aymeric

**Comment by Paul-Reed** [comment]
This is the [latest Codacy report](https://www.codacy.com/app/emoncms/dashboard/pullRequest?prid=701286), for your information.

Paul

**Comment by Paul-Reed** [comment]
I haven't looked at your last 2 commits yet, but heres some feedback using commit https://github.com/emoncms/dashboard/pull/87/commits/161b5a1207cf2c814b49dfee7c4cd4324a6ada16 

**Humidex**
Can the value display the unit, such as 28**°C**. You have done this in the frostpoint widget and appears as an option as 'Unit Position'.

**Frostpoint**
Not sure that the correct values are being returned. Using the examples in your reference - http://www.e-lab.de/downloads/DOCs/SHT11appnote2.pdf for example;
RH=10% T=25C the expected Dewpoint should be -8.69°C
Feeding those values into the widget returns -- °C

Nice formatting options of font weight, style & size. It would be good to standardize these options throughout the other emoncms widgets at some stage in the future.

**Comment by thib66** [comment]
-- °C is diplayed because when external temperature is greater than 0°C frostpoint has no sense.
Frostpoint is only usefull for a negative temperature. 
Humidex is expressed without unit.
concerning  formatting options of font weight, style & size I will implement this for existing dewpoint

**Comment by Paul-Reed** [comment]
> Humidex is expressed without unit.

Although the widget is called 'humidex', I assumed that it was in fact based upon 'heat index' which does use a unit.
Humidex is derived from the dew point, whilst the heat index is derived from %humidity (which you are doing) hence my assumption. See [this reference.](https://en.wikipedia.org/wiki/Humidex)

 

> I will implement this for existing dewpoint

Thanks, please make a separate PR though! 

Paul

**Comment by thib66** [comment]
hello, 
the last changes have been done to the code. there are some issues related to _Tr() translation functions that cannot be fixed and also camelcase issues not fixed due to the global structure of the CMS.
Concerning the humidex, I used the simplified formula for the canadian one which is expressed without unit.
See reference : https://www.theweathernetwork.com/news/articles/humidex-vs-heat-index-whats-the-difference/10243
If I have the time and if desired I will create the american Heat Index

**Comment by Paul-Reed** [comment]
Already merged via https://github.com/emoncms/dashboard/pull/88

**Pull request closed without merging**
