### PR TITLE
Make undo and redo set modified state correctly

### LINKED ISSUE #34: Undo doesn't raise modified state.
Steps to reproduce:
1) Make some changes to a dashboard.
2) Save the dashboard.
3) Press undo.

Expected action:
The save button goes orange and you can save the dashboard.

Actual action:
The save button stays green and you can't save the dashboard.

### PR DESCRIPTION
**Pull request by mattjgalloway**
We had an issue where if you made some changes, then saved, then did an undo or redo, you couldn't save until you made another change. This was because undo and redo weren't setting the modified state. This fixes that.

Fixes #34.

### CODE REVIEW

**Comment by Paul-Reed** [comment]
Issue still persists here Matt.
Stock dashboard clone & diff applied.

Paul

**Comment by mattjgalloway** [comment]
> Issue still persists here Matt.
> Stock dashboard clone & diff applied.

Does it happen when you do exactly the steps I outline in #34? I'm just wondering if there's another case that I'm missing.

**Comment by Paul-Reed** [comment]
Yes, exactly the same.

Paul

**Comment by Paul-Reed** [comment]
This is what I see Matt;

undo

Paul

**Comment by mattjgalloway** [comment]
Oh wow, that's very strange. I do those exact steps and it doesn't do that. Gah! I'll see if I'm not going mad...

**Comment by Paul-Reed** [comment]
Sorry Matt, re-applied the diff again (after trying https://github.com/emoncms/dashboard/pull/33) and now for some reason it's working as you expected.
I had flushed my browser cache previously, and also checked git status so I know that the diff was correctly applied. So can't explain!!!

Anyway, all good now.

Paul

**Comment by mattjgalloway** [comment]
Great stuff!

**Pull request merged**
