### PR TITLE
Add key bindings to move things around the dashboard editor

### PR DESCRIPTION
**Pull request by mattjgalloway**
This adds key bindings when on the dashboard editor so that you can move items around with the arrow keys. Items move by 1 grid size unit in whichever direction of arrow you press.

### CODE REVIEW

**Comment by Paul-Reed** [comment]
I was about to comment on that!!
Thanks

**Comment by Paul-Reed** [comment]
It's still not happening for me, I have your latest version of designer.js and the arrow keys have no effect other than move the page up or down a little.
Using windows 10, tried Firefox, Chrome & Explorer (current versions), clearing their caches, even trying incognito windows to no avail.

**Comment by mattjgalloway** [comment]
@Paul-Reed - Hmm that's weird! I'm mainly using Chrome, but it also works for me in Safari. How odd! I'm using a Mac, but I can't believe that would make a difference here. Unless the key code is different for the arrow keys...

What does this website say when you press the arrow keys on your keyboard?
http://keycode.info/

**Comment by Paul-Reed** [comment]
37, 38, 39 & 40, identical to your commit.

**Comment by mattjgalloway** [comment]
@Paul-Reed - can you try with that latest commit please? I switched it to binding through jquery which may standardise things across browsers/OSes for us.

**Comment by Paul-Reed** [comment]
The jquery switch on your last commit has now enabled the arrow keys. and appear to be now working as intended. Great!
I'll do a little more testing, but it's looking good, and especially as it nudges the grid distance which is now user selectable.

**Comment by mattjgalloway** [comment]
Yeh, I found this incredibly useful. Moving things around by dragging the centre is rather frustrating especially when the centre isn't very visible (thus hard to find) due to the colour of the widget.

**Comment by Paul-Reed** [comment]
Thanks Matt, works fine now provided the cache is refreshed to clear the javascript. No errors, and no detrimental issues for android/ios.
Two very much appreciated merges :+1:

**Comment by Paul-Reed** [comment]
Matt, one thing that I have found;
If moving objects with a mouse, it was extremely difficult to move objects off of the page, so they could always be recovered.
However, using the arrow keys, objects can be moved off-page, and if focus is lost they cannot be retrieved/deleted.
Could restrictions be applied to stop this?

Paul

**Comment by mattjgalloway** [comment]
Ah yes. That'll need fixing. Good spot. I'll work on that ASAP.

I've always wondered why the page isn't infinite anyway, and just scroll as far as is needed to view every element. But maybe there's a reason why that is hard to implement.

**Comment by mattjgalloway** [comment]
@Paul-Reed - fixed with #10.

**Pull request merged**
