### PR TITLE
led widget optimization

### PR DESCRIPTION
**Pull request by thib66**
obsolete and unused draw_binary_led suppressed
add an option with 2 choices of style :
- actual style with colour gradients
- style without colour gradients in order to have a flat design (in fact function developed in the past for IE8, but probably this have never worked for this browser ...)

### CODE REVIEW

**Comment by Paul-Reed** [comment]
Aymeric, there are merge  conflicts with this PR, can you update your local fork to the current master, to resolve the conflicts please.

Paul

**Comment by thib66** [comment]
I tried to do this on github.com but I unable to see how to update my local fork
Aymeric

**Comment by Paul-Reed** [comment]
[This](https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository) may help

Paul

**Comment by Paul-Reed** [comment]
The image below shows why there is a conflict, it's because you merged changes to the LED widget on the 26th June, but this PR is based upon an earlier version of master (21st June) which does not include the PR committed on the 26th June.

**Comment by thib66** [comment]
Paul, I am a bit lost, what I have to do to resolve conflict? is closing this PR and opening a PR from a new fork would be the simplest solution?
Regards,
Aymeric

**Comment by Paul-Reed** [comment]
I'm sure that there would be a way around this, possibly reverting https://github.com/emoncms/dashboard/commit/60e0dee43fb338a83b7814eb023b75b9a5bf2c76 and then merging this PR, but I also find git difficult to deal with, and wouldn't be confident that it would be successful.
Certainly creating a new fork and applying your changes would work, and possibly the easiest solution...

If you had been making changes in a different widget, there wouldn't have been a problem.

Paul

**Comment by thib66** [comment]
PR closed and #106 opened

**Pull request closed without merging**
