### PR TITLE
thermometer improvement

### PR DESCRIPTION
**Pull request by thib66**
Add customized error message
Fix bug when input is updated with the same value
Before the fix, error message was displayed
now the height of mercury for the value is not displayed when timeout is reached

### CODE REVIEW

**Comment by thib66** [comment]
Hello,
May you have a look of the 5 PR opened since November?
Thanks a lot,
Regards,
Aymeric

**Comment by Paul-Reed** [comment]
Hi Aymeric, thanks for the prompt, sorry it's taken so long to review...
If they are not reviewed by other team members, I'll ensure it's done within the coming week.

Best Wishes
Paul

**Comment by thib66** [comment]
Hello Paul,
thanks for your help and best wishes as well.
Regards,
Aymeric

**Comment by Paul-Reed** [comment]
Hi Aymeric.

I've reviewed & merged your PR's into a new dashboard branch - `thib66_enhancements`

It's great that you've given some thought about making the existing widgets more resilient through better error messaging, just sorry that we haven't reviewed them sooner!

If you could please confirm that the French Localization is good to go, I'll merge the branch into Master.

Best Wishes
Paul

**Pull request merged**
