### PR TITLE
Feedvalue widget enhancements

### PR DESCRIPTION
**Pull request by firefox7518**
Enhancements done to the feedvalue widget to allow for choosing font options, size, position of unit and color.

### CODE REVIEW

**Comment by Paul-Reed** [comment]
Hi Andreas, I think there are still a number of issues with this PR;
**Font Size** - when anything less than 14pt is selected, 40pt is displayed.
**Font** - does not display all font styles, for example Helvetica Neue is a sans-serif font, but is being displayed with serifs, and Arial Narrow is displayed as Helvetica.

The Codacy report still shows a number of errors - https://www.codacy.com/app/emoncms/dashboard/pullRequest?prid=667280

Are the conditional statements correct with regard to the semicolon positioning? For example, shouldn't;
if (size == 0){size = 6};
if (size == 1){size = 8};
if (size == 2){size = 10};
if (size == 3){size = 12};

be;
if (size == 0){size = 6;}
if (size == 1){size = 8;}
if (size == 2){size = 10;}
if (size == 3){size = 12;}

etc...

Paul

**Comment by firefox7518** [comment]
Hi Paul

Look I've just reverted to my code which is working since months on my prod EMonCMS on hundreds of dashbaords. You can try to do the changes proposed by Codacrap but you will find that the code will not work anymore. Because of the found "errors" I changed it to what it suggested which actually rendered the code unfunctional for me. If you have the hours of time to fix something which is actually working you can of course go ahead and do it but I will now stop it here. I do not have the time for this and I will not completely rewrite the whole base code of it which was written by Trystan.

image

**Comment by Paul-Reed** [comment]
Hi Andreas, I wasn't expecting you to sort all of the Codacy problems, as many are deep rooted and would need wholesale changes, just those added through **your** changes. But if you are busy, that's OK, we'll try and sort some of them in due course.
But... the main reason for my last comment was that there was 2 distinct problems with selecting font style and font size. If they have now been fixed via https://github.com/emoncms/dashboard/pull/85/commits/361c857d76b9bb1c9f337300c5399e9fda764dd0 I'll happily take another look tonight.

Paul

**Comment by Paul-Reed** [comment]
Thanks Andreas, https://github.com/emoncms/dashboard/commit/361c857d76b9bb1c9f337300c5399e9fda764dd0 has resolved the 2 issues raised, and the changes to the conditional statements has improved the Codacy score.

Regards

Paul

**Pull request merged**
