### PR TITLE
Create thermometer_render.js

### PR DESCRIPTION
**Pull request by thib66**
image

### CODE REVIEW

**Comment by Paul-Reed** [comment]
The codacy score is let down by most of the variables not utilizing Camelcase.
For example, using `displayValue` instead of `display_value`

Paul

**Comment by thib66** [comment]
Hello Paul,
the code should be better.
is there a way to indicate to codacy to ignore undefined **__Tr_** function? (used for localization).
div1 and div2 are tag objects i do not know if we can declare those objects as variables.
concerning the functions I prefer to keep underscores as this particular syntax is used by the emoncms structure.
Regards

**Comment by Paul-Reed** [comment]
That's much better, thanks.
I'm not sure that the tag objects need to be declared, but the parentheses doesn't look quite right.
Are tag objects normally <enclosed> ?? 

Paul

**Comment by thib66** [comment]
helloPaul,
tag objects are normally enclosed <>, if you use jquery this is the case but not when using document.createElement.
Regards,
Aymeric

**Comment by Paul-Reed** [comment]
Aymeric, another useful widget, many thanks.

Paul

**Comment by Paul-Reed** [comment]
Aymeric, any ideas about this issue created in the forum - https://community.openenergymonitor.org/t/new-thermometer-widget-added-to-dashboard/4752

**Comment by thib66** [comment]
Hello Paul,
bug not reproduced with FireFox 54.0.1 and Edge. But reproduced with IE11 as described.
Regards,
Aymeric

**Comment by thib66** [comment]
Paul, 
I have improved the js scripts yesterday for bar, dial and thermometer widgets with declaration of the variables for the tooltips. I do not have errors with those new scripts in IE11.
But #126 should be validated before destroying and creating again my fork in github in order to correctly commit the new fixes. Could you have a look a this PR?
Regards,
Aymeric

**Pull request merged**
