### PR TITLE
Create thresholds_render.js

### PR DESCRIPTION
**Pull request by thib66**
This widget is similar to isactivefeed one in terms of "look and feel" but instead of indicating the status of update delay, this widget indicates if the feed value is above or below thresholds

### CODE REVIEW

**Comment by glynhudson** [comment]
Thanks! Would it be possible to include a screen grab in the PR to illustrate operation? Have you aware of the Codacy recommendations? I'm not sure if they are relevant or not?

**Comment by thib66** [comment]
Hello,
image
if temperature (feed) >16 : 
image
if 14< temperature (feed) < 16 : 
image
if temperature (feed) <14 : 
image

Codacy recommandations are the same compared with isactivefeed widget, so there are not relevant.
Regards,
Aymeric

**Comment by thib66** [comment]
sorry the first capture is wrong
image

**Comment by glynhudson** [comment]
Thanks a lot 👍

**Pull request merged**
