### PR TITLE
Allow selecting multiple elements at once

### PR DESCRIPTION
**Pull request by mattjgalloway**
This allows you to select multiple elements at the same time, so that you can move them around and bring them forwards, backwards.

Current limitation is that moving around is only supported by using the arrow keys. I want to support moving using the mouse, but it was more complicated. The way it is is still very useful though, IMO.

Would love some feedback on this.

### CODE REVIEW

**Comment by Paul-Reed** [comment]
Matt, were you aware of this, when multiple elements are dragged off screen;

edge

Paul

**Comment by mattjgalloway** [comment]
Hmm. Yes, now I seem to recall seeing that! (Did this work a while ago and forgot about this problem).

WDYT? On one hand I don't think it's that bad. But it's not ideal either. Let me see if I can fix it quickly.

**Comment by mattjgalloway** [comment]
@Paul-Reed - there, fixed. It's amazing how you see the woods for the trees when you just come back to it a while later!

**Comment by Paul-Reed** [comment]
Great! this is a really nice addition. Moving each element individually and aligning them again was a pain!.
Thanks Matt.

Paul

**Pull request merged**
