### PR TITLE
Isactivefeed optimization

### PR DESCRIPTION
**Pull request by thib66**
dashboard_edit_view.php and dashboard_view.php modified in order to go back to the previous version
isactivefeed_widget.php added in order to respect emonCMS architecture

### CODE REVIEW

**Comment by thib66** [comment]
Hello,
@chaveiro , the problem of code polluting existing files should be fixed with the  last changes.
For render.js, in think there is no way to place the added code outside of the script.
Regards,
Aymeric

**Comment by Paul-Reed** [comment]
Could you also take a look at the default values (such as colour) that should be applied when none are specified please. 
Currently the default appears to be black, and not what you have coded.

Paul

**Comment by thib66** [comment]
Hello Paul, 
In fact the default colors coded are just defined to create the object in case initially there are void values (just a security). Actually I don't know how to pass default colors to pulldown lists. Is there somewhere a documentation about **_addOption_** function?
Regards,
Aymeric

**Comment by Paul-Reed** [comment]
Aah right, in that case no worries. Thanks.

On 21 Jun 2017 10:33 am, "Aymeric THIBAUT" <notifications@github.com> wrote:

Hello Paul,
In fact the default colors coded are just defined to create the object in
case initially there are void values (just a security). Actually I don't
know how to pass default colors to pulldown lists. Is there somewhere a
documentation about *addOption* function?
Regards,
Aymeric

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/emoncms/dashboard/pull/99#issuecomment-310024616>, or mute
the thread

**Comment by Paul-Reed** [comment]
Thanks Aymeric

**Comment by chaveiro** [comment]
Nice @thib66, thanks for quick response!

**Pull request merged**
