### PR TITLE
Feedvalue widget enhancements

### PR DESCRIPTION
**Pull request by firefox7518**
Enhancements done to the feedvalue widget to allow for choosing font options, size, position of unit and color.

### CODE REVIEW

**Comment by Paul-Reed** [comment]
Andreas, Codacy has reported a number of minor coding issues - see https://www.codacy.com/app/emoncms/dashboard/pullRequest?prid=667280
Most are highlighting missing curly braces, and mixed spaces and tabs.
Are you able to tidy these up please before merging (we are trying to improve the Codacy score throughout emoncms).

Paul

**Comment by firefox7518** [comment]
Did some updates on the code. Codacy does not show anything on my branch:
image

Maybe its ok now?

Andi

**Comment by Paul-Reed** [comment]
This is what I see on the PR - https://www.codacy.com/app/emoncms/dashboard/pullRequest?prid=667280   

Paul

**Comment by firefox7518** [comment]
closing this one for a new one with all the commits in one

**Pull request closed without merging**
