### PR TITLE
add min max position to the dial

### PR DESCRIPTION
**Pull request by thib66**

### CODE REVIEW

**Comment by thib66** [comment]
Before 2b97f9c : 
without-min-max
After 2b97f9c : 
with-min-max

**Comment by thib66** [comment]
image

**Comment by Paul-Reed** [comment]
Thanks Aymeric, a nice and useful addition.
I was thinking how we could display the actual min and max values, but it then starts to look very congested. I'm sure you've considered the same.

Paul

**Comment by thib66** [comment]
Hello Paul,
I tried to display min and max values discreetly in the graph, there is perhaps another way to diplay this information.
If you have any idea, i will try to integrate another representation in the widget.
Regards,
Aymeric

**Comment by Paul-Reed** [comment]
Thanks, would it be possible to use a tooltip, so the value is only shown on mouseover?
...just a thought!

Paul

**Comment by thib66** [comment]
Hello Paul
yes the functionality is available with #115.
Enjoy!
Aymeric

**Pull request merged**
