### PR TITLE
additional options and quality code improvement

### PR DESCRIPTION
**Pull request by thib66**
Add decimals and units position options and quality code improvement

### CODE REVIEW

**Comment by glynhudson** [comment]
Nice! Could you attache some screen grabs to illustrate your changes to help the team review and document? Cheers.

**Comment by thib66** [comment]
decimals
decimals_position
decimals_position_result
decimals_result

**Comment by thib66** [comment]
hello,
Please let me know if the previous screen shots are useful for you.
Regards,
Aymeric

**Comment by thib66** [comment]
Hello,  and also may you give me the direct link to the actual end user documentation?
Regards,
Aymeric

**Comment by Paul-Reed** [comment]
Thank you. This is a nice addition to allow users to select digital precision, or revert back to 'automatic' selection. Also appreciate the code quality improvements.

End user documentation can be found;

Guide - https://guide.openenergymonitor.org/
Resources - https://guide.openenergymonitor.org/technical/resources/
Forum - https://community.openenergymonitor.org/
and of course - https://github.com/emoncms/emoncms/tree/master/docs

Paul

**Pull request merged**
