### PR TITLE
Bar Enhancements

### PR DESCRIPTION
**Pull request by firefox7518**
- Allow Title
- Allow Label colour
- Allow font selection
- made the value slightly smaller to make it fit better into the bar when graduations are off.
- should not break existing bar widgets. Tested locally but needs testing from others as well.

### CODE REVIEW

**Comment by firefox7518** [comment]
Now you can do something like this: 
image

This reminds me a little bit of LCARS Star Trek design :-) I would love to have a theme like LCARS for EmonCMS :-)

**Comment by Paul-Reed** [comment]
I don't want this feature to delay the merging of the palette work, so can you change your barwidget PR to the **feature/barwidget-rework** branch please, and then we can separate the two, and deal with them individually.

Thanks

Paul

**Comment by firefox7518** [comment]
changed

**Comment by Paul-Reed** [comment]
Hi Andreas, I'm not able to change the font style, it remains the same no matter which style I choose.
For example, in the screenshot below, I've selected and saved Comic Sans MS.

temp

Paul

**Comment by firefox7518** [comment]
Hi Paul

Thanks for the feedback. I think I now fixed it. It seems to work here on my local dev machine:
image
left bar is old bar_render.js created and the right one the new one. It did not change the font of the already existing one so this looks good.

**Comment by Paul-Reed** [comment]
Thanks Andreas, yes working now.

Paul

**Comment by firefox7518** [comment]
Did you see any sign of none working standard bar widgets?

**Comment by Paul-Reed** [comment]
No, I prepared some bar widgets before loading your changes, and they integrated well with no problems for me.

Paul

**Pull request merged**
