### PR TITLE
Curl Widget

### PR DESCRIPTION
**Pull request by RDCH106**
- Added Curl Widget

Very useful to create action buttons in the dashboards. The implementation of the widget was originally created by [brutzler](https://openenergymonitor.org/emon/node/6394). I have refined it a little bit more.

Screenshot of the widget in the dashboard:

on_off_buttons

Screenshot of the configuration panel:

curl_conf

It can be used to for remote activation of the desired devices or desired processes in Node-Red using http request.

### CODE REVIEW

**Comment by glynhudson** [comment]
Nice! Thanks, works great. Just tested posting to emoncms localhost (itself!)

emoncms dashboard edit

**Comment by glynhudson** [comment]
Do you think you could do a quick post about this addition on our community
forums in the emoncms section to notify our users. Thanks +1

- sent from my mobile device

**Comment by RDCH106** [comment]
Sure!
I will write it in a free moment.

**Comment by glynhudson** [comment]
👍

**Comment by glynhudson** [comment]
Just a screen shot and a couple of lines of explanation will be fine. Cheers

**Pull request merged**
